ALTER TABLE questions
  DROP COLUMN wrong_attempts,
  DROP COLUMN right_attempts,
  DROP COLUMN total_attempts;

CREATE TABLE question_statistics(
  id int(11) auto_increment PRIMARY KEY,
  question VARCHAR(255) UNIQUE,
  wrong_attempts INTEGER NOT NULL,
  right_attempts INTEGER NOT NULL,
  total_attempts INTEGER NOT NULL,
  FOREIGN KEY (question) REFERENCES questions (description) ON UPDATE CASCADE ON DELETE CASCADE
);

INSERT INTO question_statistics (question, wrong_attempts, right_attempts, total_attempts) VALUES
("Los signos clínicos de ostertagiasis pueden ser:" ,0,0,0),
("Haemonchus spp ejerce su acción patógena en:" ,0,0,0),
("La ostertagiasis se trata con:" ,0,0,0),
("Los signos clínicos de fascioliasis pueden ser:" ,0,0,0),
("La fascioliasis se trata con:" ,0,0,0),
("Diarrea es signo clínico característico de:" ,0,0,0),
("Anemia y edema son característicos de:" ,0,0,0),
("Es signo característico de dictiocaulosis:" ,0,0,0),
("La coccidiosis se trata con:" ,0,0,0),
("Albendazol es eficaz para tratar:" ,0,0,0),
("La posología de Enrofloxacina es:" ,0,0,0),
("La posología de Danofloxacina es:" ,0,0,0),
("La posología de Florfenicol es:" ,0,0,0),
("La posología de Oxitetraciclina L.A. es:" ,0,0,0),
("La posología de Clorhidrato de Oxitetraciclina es:" ,0,0,0),
("La posología de Amoxicilina es:" ,0,0,0),
("La dosis y vía de Adm. de Tilmicosina para Ap. Respiratorio es:" ,0,0,0),
("La dosis y vía de Adm. de Tilmicosina para Ojo o Pie es:" ,0,0,0),
("La posología de Enrofloxacina L.A. es:" ,0,0,0),
("La posología de Danofloxacina L.A. es:" ,0,0,0),
("Para Colibacilosis está/n indicado/s:" ,0,0,0),
("La/s Vía/s de Administración de las Penicilinas Naturales son:" ,0,0,0),
("Para Salmonellosis está/n indicado/s:" ,0,0,0),
("Para Metafilaxia de Ap. Respiratorio está/n indicado/s:" ,0,0,0),
("Para infecciones oculares está/n indicado/s:" ,0,0,0),
("La dosis y vía de Pilocarpina es:" ,0,0,0),
("La dosis y vía de Neostigmina es:" ,0,0,0),
("La dosis y vía de Atropina es:" ,0,0,0),
("La dosis y vía de Metescopolamina es:" ,0,0,0),
("La dosis y vía de Butilescopolamina es:" ,0,0,0),
("La dosis y vía de Benzetimida es:" ,0,0,0),
("La dosis y vía de Loperamida es:" ,0,0,0),
("La dosis de Bicarbonato de Sodio por Vía Oral es:" ,0,0,0),
("La dosis Total, para un bovino adulto de Dihidroxi Antraquinino es:" ,0,0,0),
("La dosis de Sulfato de Magnesio pos Vía Oral es:" ,0,0,0),
("La dosis del Albendazol para nematodos es:" ,0,0,0),
("La dosis de Albendazol para larvas inhibidas de Ostertagia es:" ,0,0,0),
("La dosis de Albendazol para Fasciola Hepática es:" ,0,0,0),
("La dosis de Ivermectina al 1% es:" ,0,0,0),
("La dosis de Ivermectina al 3,15% es:" ,0,0,0);
